fix husky pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -6,11 +6,16 @@ EXCLUDED_BRANCH="main"
 
 BRANCH_NAME=$(git symbolic-ref --short HEAD 2>/dev/null)
 
-if [ "$BRANCH_NAME" = "main" || "$BRANCH_NAME" = "dev" ]; then
+EXPECTED_PATTERN="^(feature|bugfix|hotfix|refactor|docs|setup)/.*"
+
+if [ "$BRANCH_NAME" = "$EXCLUDED_BRANCH" ]; then
     echo "Skipping pre-commit hook on branch: $EXCLUDED_BRANCH"
-    echo "Running lint-staged"
-    npx lint-staged
     exit 0 # Exit without performing any actions
+fi
+
+if ! [[ $BRANCH_NAME =~ $EXPECTED_PATTERN ]]; then
+    echo "Error: Invalid branch name. Branch names must match the pattern: $EXPECTED_PATTERN"
+    exit 1
 fi
 
 echo "Running lint-staged"
